Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrotiX.Models;
using FrotiX.Repository.IRepository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrotiX.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class FornecedorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public FornecedorController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get()
        {
            return Json(new { data = _unitOfWork.Fornecedor.GetAll() });
        }

        [Route("Delete")]
        [HttpPost]        
        public IActionResult Delete(FornecedorViewModel model)
        {
            if (model != null && model.FornecedorId != Guid.Empty)
            {
                var objFromDb = _unitOfWork.Fornecedor.GetFirstOrDefault(u => u.FornecedorId == model.FornecedorId);
                if (objFromDb != null)
                {
                    var contrato = _unitOfWork.Contrato.GetFirstOrDefault(u => u.FornecedorId == model.FornecedorId);
                    if (contrato != null)
                    {
                        return Json(new { success = false, message = "Existem contratos associados a esse fornecedor" });
                    }
                    _unitOfWork.Fornecedor.Remove(objFromDb);
                    _unitOfWork.Save();
                    return Json(new { success = true, message = "Fornecedor removido com sucesso" });
                }
            }
            return Json(new { success = false, message = "Erro ao apagar Fornecedor" });
        }

        [Route("UpdateStatusFornecedor")]
        public JsonResult UpdateStatusFornecedor(Guid Id)
        {
            if (Id != Guid.Empty)
            {
                var objFromDb = _unitOfWork.Fornecedor.GetFirstOrDefault(u => u.FornecedorId == Id);
                string Description = "";
                int type = 0;

                if (objFromDb != null)
                {
                    if (objFromDb.Status == true)
                    {
                        //res["success"] = 0;
                        objFromDb.Status = false;
                        Description = string.Format("Atualizado Status do Fornecedor [Nome: {0}] (Inativo)", objFromDb.DescricaoFornecedor);
                        type = 1;
                    }
                    else
                    {
                        objFromDb.Status = true;
                        Description = string.Format("Atualizado Status do Fornecedor  [Nome: {0}] (Ativo)", objFromDb.DescricaoFornecedor);
                        type = 0;
                    }
                    _unitOfWork.Fornecedor.Update(objFromDb);
                }
                return Json(new { success = true, message = Description, type = type });
            }
            return Json(new { success = false });
        }

    }
}

Pages/AtaRegistroPrecos/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrotiX.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using FrotiX.Services;
using FrotiX.Models;
using System.IO;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace FrotiX.Pages.AtaRegistroPrecos
{

    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        private readonly INotyfService _notyf;

        public static Guid ataId;


        public UpsertModel(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment, INotyfService notyf)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
            _notyf = notyf;
        }


        [BindProperty]
        public AtaRegistroPrecosViewModel AtaObj { get; set; }

        private void SetViewModel()
        {
            AtaObj = new AtaRegistroPrecosViewModel
            {
                FornecedorList = _unitOfWork.Fornecedor.GetFornecedorListForDropDown(),
                AtaRegistroPrecos = new Models.AtaRegistroPrecos()
            };
        }

        public IActionResult OnGet(Guid? id)
        {
            SetViewModel();

            if (id != null && id != Guid.Empty)
            {
                AtaObj.AtaRegistroPrecos = _unitOfWork.AtaRegistroPrecos.GetFirstOrDefault(u => u.AtaId == id);
                if (AtaObj == null)
                {
                    return NotFound();
                }
            }
            return Page();
        }

        
        public IActionResult OnPostSubmit()
        {
            if (!ModelState.IsValid)
            {
                SetViewModel();
                return Page();
            }

            var existeAta = _unitOfWork.AtaRegistroPrecos.GetFirstOrDefault(u => (u.AnoAta == AtaObj.AtaRegistroPrecos.AnoAta) && (u.NumeroAta == AtaObj.AtaRegistroPrecos.NumeroAta));
            if (existeAta != null)
            {
                _notyf.Error("Já existe uma Ata com esse número!", 3);
                SetViewModel();
                return Page();
            }

            _unitOfWork.AtaRegistroPrecos.Add(AtaObj.AtaRegistroPrecos);

            _unitOfWork.Save();

            _notyf.Success("Ata adicionada com sucesso!", 3);

            return RedirectToPage("./Index");
        }

        public IActionResult OnPostEdit(Guid id)
        {
            if (!ModelState.IsValid)
            {
                SetViewModel();
                AtaObj.AtaRegistroPrecos.AtaId = id;
                return Page();
            }

            AtaObj.AtaRegistroPrecos.AtaId = id;

            var existeAta = _unitOfWork.AtaRegistroPrecos.GetFirstOrDefault(u => (u.AnoAta == AtaObj.AtaRegistroPrecos.AnoAta) && (u.NumeroAta == AtaObj.AtaRegistroPrecos.NumeroAta));
            if (existeAta != null && existeAta.AtaId != AtaObj.AtaRegistroPrecos.AtaId)
            {
                _notyf.Error("Já existe uma Ata com esse número!", 3);
                SetViewModel();
                AtaObj.AtaRegistroPrecos.AtaId = id;
                return Page();
            }

            _unitOfWork.AtaRegistroPrecos.Update(AtaObj.AtaRegistroPrecos);
            _unitOfWork.Save();

            _notyf.Success("Ata atualizada com sucesso!", 3);

            return RedirectToPage("./Index");
        }

    }


}

Pages/Combustivel/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrotiX.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using FrotiX.Services;
using FrotiX.Models;
using System.IO;
using Microsoft.Extensions.Configuration;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace FrotiX.Pages.Combustivel
{

    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<IndexModel> _logger;
        private readonly INotyfService _notyf;

        public UpsertModel(IUnitOfWork unitOfWork, ILogger<IndexModel> logger, INotyfService notyf)
        {
            _unitOfWork = unitOfWork;
             _logger = logger;
            _notyf = notyf;
        }


        [BindProperty]
        public Models.Combustivel CombustivelObj { get; set; }

        public IActionResult OnGet(Guid? id)
        {
            CombustivelObj = new Models.Combustivel();
            if (id != null && id != Guid.Empty)
            {
                CombustivelObj = _unitOfWork.Combustivel.GetFirstOrDefault(u => u.CombustivelId == id);
                if (CombustivelObj == null)
                {
                    return NotFound();
                }
            }
            return Page();

        }

        
        public IActionResult OnPostSubmit()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Verifica Duplicidades
            var existeCombustivel = _unitOfWork.Combustivel.GetFirstOrDefault(u => u.Descricao.ToUpper() == CombustivelObj.Descricao.ToUpper());
            if (existeCombustivel != null && existeCombustivel.CombustivelId != CombustivelObj.CombustivelId)
            {
                _notyf.Error("Já existe um combustível com esse nome!", 3);
                return Page();
            }


            if (CombustivelObj.CombustivelId == Guid.Empty)
            {
                _notyf.Success("Combustível adicionado com sucesso!", 3);
                _unitOfWork.Combustivel.Add(CombustivelObj);
            }
            else
            {
                _notyf.Success("Combustível atualizado com sucesso!", 3);
                _unitOfWork.Combustivel.Update(CombustivelObj);
            }
            _unitOfWork.Save();
             return RedirectToPage("./Index");
        }


    }


}

Pages/Contrato/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrotiX.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using FrotiX.Services;
using FrotiX.Models;
using System.IO;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace FrotiX.Pages.Contrato
{

    [Consumes("application/json")]
    [IgnoreAntiforgeryToken]
    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<IndexModel> _logger;
        private readonly IWebHostEnvironment _hostingEnvironment;

        private readonly INotyfService _notyf;

        public static Guid contratoId;


        public UpsertModel(IUnitOfWork unitOfWork, ILogger<IndexModel> logger, IWebHostEnvironment hostingEnvironment, INotyfService notyf)
        {
            _unitOfWork = unitOfWork;
             _logger = logger;
            _hostingEnvironment = hostingEnvironment;
            _notyf = notyf;
        }


        [BindProperty]
        public ContratoViewModel ContratoObj { get; set; }

        private void SetViewModel()
        {
            ContratoObj = new ContratoViewModel
            {
                FornecedorList = _unitOfWork.Fornecedor.GetFornecedorListForDropDown(),
                Contrato = new Models.Contrato()
            };
        }

        public IActionResult OnGet(Guid? id)
        {
            SetViewModel();

            if (id != null && id != Guid.Empty)
            {
                ContratoObj.Contrato = _unitOfWork.Contrato.GetFirstOrDefault(u => u.ContratoId == id);
                if (ContratoObj == null)
                {
                    return NotFound();
                }
            }
            else
            {
                ContratoObj.Contrato.Status = true;
            }
            return Page();
        }


        //Insere Novo Contrato
        //====================
        public JsonResult OnPostInsereContrato(Models.Contrato contrato)
        {
             var existeContrato = _unitOfWork.Contrato.GetFirstOrDefault(u => (u.AnoContrato == contrato.AnoContrato) && (u.NumeroContrato == contrato.NumeroContrato));
            if (existeContrato != null && existeContrato.ContratoId != contrato.ContratoId)
            {
                _notyf.Error("Já existe um contrato com esse número!", 3);
                SetViewModel();
                return new JsonResult(new { data = "00000000-0000-0000-0000-000000000000" });
            }

            _unitOfWork.Contrato.Add(contrato);

            _unitOfWork.Save();

            return new JsonResult(new { data = contrato.ContratoId, message = "Contrato Adicionado com Sucesso" });
        }

        //public IActionResult OnPostSubmit()
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        SetViewModel();
        //        return Page();
        //    }

        //    var existeContrato = _unitOfWork.Contrato.GetFirstOrDefault(u => (u.AnoContrato == ContratoObj.Contrato.AnoContrato) && (u.NumeroContrato == ContratoObj.Contrato.NumeroContrato));
        //    if (existeContrato != null && existeContrato.ContratoId != ContratoObj.Contrato.ContratoId)
        //    {
        //        _notyf.Error("Já existe um contrato com esse número!", 3);
        //        SetViewModel();
        //        return Page();
        //    }

        //    _unitOfWork.Contrato.Add(ContratoObj.Contrato);

        //    _unitOfWork.Save();

        //     return RedirectToPage("./Index");
        //}

        public IActionResult OnPostEdit(Guid id)
        {
            if (!ModelState.IsValid)
            {
                SetViewModel();
                ContratoObj.Contrato.ContratoId = id;
                return Page();
            }

            ContratoObj.Contrato.ContratoId = id;

            var existeContrato = _unitOfWork.Contrato.GetFirstOrDefault(u => (u.AnoContrato == ContratoObj.Contrato.AnoContrato) && (u.NumeroContrato == ContratoObj.Contrato.NumeroContrato));
            if (existeContrato != null && existeContrato.ContratoId != ContratoObj.Contrato.ContratoId)
            {
                _notyf.Error("Já existe um contrato com esse número!", 3);
                SetViewModel();
                ContratoObj.Contrato.ContratoId = id;
                return Page();
            }

            _unitOfWork.Contrato.Update(ContratoObj.Contrato);
            _unitOfWork.Save();

            _notyf.Success("Contrato atualizado com sucesso!", 3);

            return RedirectToPage("./Index");
        }

    }


}

Pages/Empenho/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FrotiX.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using FrotiX.Services;
using FrotiX.Models;
using System.IO;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Hosting;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace FrotiX.Pages.Empenho
{
    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<IndexModel> _logger;
        private readonly IWebHostEnvironment _hostingEnvironment;

        private readonly INotyfService _notyf;

        public static Guid empenhoId;


        public UpsertModel(IUnitOfWork unitOfWork, ILogger<IndexModel> logger, IWebHostEnvironment hostingEnvironment, INotyfService notyf)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;
            _notyf = notyf;
        }


        [BindProperty]
        public EmpenhoViewModel EmpenhoObj { get; set; }

        private void SetViewModel()
        {
            EmpenhoObj = new EmpenhoViewModel
            {
                ContratoList = _unitOfWork.Contrato.GetContratoListForDropDown("", 1),
                AtaList = _unitOfWork.AtaRegistroPrecos.GetAtaListForDropDown(1),
                Empenho = new Models.Empenho()
            };
        }

        public IActionResult OnGet(Guid? id)
        {
            SetViewModel();

            if (id != null && id != Guid.Empty)
            {
                EmpenhoObj.Empenho = _unitOfWork.Empenho.GetFirstOrDefault(u => u.EmpenhoId == id);
                if (EmpenhoObj == null)
                {
                    return NotFound();
                }
            }
            return Page();
        }


    }


}

Pages/Fornecedor/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FrotiX.Pages.Fornecedor
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Fornecedor/Index.cshtml
@page
@model FrotiX.Models.Fornecedor

@{
    ViewData["Title"] = "Fornecedores";
    ViewData["PageName"] = "fornecedor_index";
    ViewData["Heading"] = "<i class='fa-duotone fa-buildings'></i> Cadastros: <span class='fw-300'>Fornecedores</span>";
    ViewData["Category1"] = "Cadastros";
    ViewData["PageIcon"] = "fa-duotone fa-buildings";
}

@section HeadBlock {


}

<style>
    .fundo-cinza {
        background-color: #2F4F4F;
        color: aliceblue;
    }

    .label {
        color: white;
    }
</style>


<div class="row">
    <div class="col-xl-12">
        <div id="panel-1" class="panel">
            <div class="panel-container show">
                <div class="panel-content float-right">
                    <a href="/Fornecedor/Upsert" class="btn btn-info">
                        <i class="fa-regular fa-buildings">
                        </i> &nbsp; Adicionar Fornecedor
                    </a>
                </div>
                <div class="panel-content ">
                    <div class="box-body">
                        <br /><br />
                        <table id="tblFornecedor" class="table table-bordered table-striped" width="100%">
                            <thead>
                                <tr>
                                    <th>Descricao</th>
                                    <th>CNPJ</th>
                                    <th>Contato</th>
                                    <th>Telefone</th>
                                    <th>Status</th>
                                    <th>Ação</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section ScriptsBlock{

    <script src="~/js/cadastros/fornecedor.js"></script>


}

Pages/Fornecedor/Upsert.cshtml
@page
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers

@model FrotiX.Pages.Fornecedor.UpsertModel

@{ ViewData["Title"] = "Fornecedores";
    ViewData["PageName"] = "fornecedor_upsert";
    ViewData["Heading"] = "<i class='fa-duotone fa-buildings'></i> Cadastros: <span class='fw-300'>Fornecedores</span>";
    ViewData["Category1"] = "Cadastros";
    ViewData["PageIcon"] = "fa-duotone fa-buildings"; }

<style>
    .form-control-xs {
        height: calc(1em + .775rem + 2px) !important;
        padding: .125rem .25rem !important;
        font-size: .75rem !important;
        line-height: 1.5;
        border-radius: .2rem;
    }

    .label {
        margin-bottom: -5px;
        margin-top: 10px;
    }

    input[type=checkbox] {
        vertical-align: middle;
        position: relative;
        bottom: 1px;
    }

</style>

@section HeadBlock {
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
}


<form method="post" asp-action="Upsert">
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-container show">
                    <div class="panel-content">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        @if (Model.FornecedorObj.FornecedorId != Guid.Empty)
                        {
                            <input type="hidden" asp-for="FornecedorObj.FornecedorId" />
                        }

                        <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                            <h2 class="text-primary">@(Model.FornecedorObj.FornecedorId != Guid.Empty ? "Atualizar " : "Criar ") Fornecedor</h2>
                        </div>

                        <div class="col-8 pt-3">

                            <div class="row">
                                <div class="col-4">
                                    <div class="form-group">
                                        <label class="label font-weight-bold" asp-for="FornecedorObj.CNPJ"></label>
                                        <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.CNPJ"></span>
                                        <input id="cnpj" class="form-control form-control-xs" asp-for="FornecedorObj.CNPJ" placeholder="Insira o CNPJ" />
                                    </div>
                                </div>
                                <div class="col-8">
                                    <div class="form-group">
                                        <label class="label font-weight-bold" asp-for="FornecedorObj.DescricaoFornecedor"></label>
                                        <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.DescricaoFornecedor"></span>
                                        <input class="form-control form-control-xs" asp-for="FornecedorObj.DescricaoFornecedor" placeholder="Insira a razão social do fornecedor" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-9">
                                    <div class="form-group font-weight-bold">
                                        <label class="label" asp-for="FornecedorObj.Contato01"></label>
                                        <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.Contato01"></span>
                                        <input class="form-control form-control-xs" asp-for="FornecedorObj.Contato01" placeholder="Insira o nome do contato" />
                                    </div>
                                </div>
                                <div class="col-3">
                                    <div class="form-group">
                                        <label class="label font-weight-bold" asp-for="FornecedorObj.Telefone01"></label>
                                        <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.Telefone01"></span>
                                        <input class="form-control form-control-xs" asp-for="FornecedorObj.Telefone01" placeholder="Insira o telefone do contato" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-9">
                                    <div class="form-group font-weight-bold">
                                        <label class="label" asp-for="FornecedorObj.Contato02"></label>
                                        <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.Contato02"></span>
                                        <input class="form-control form-control-xs" asp-for="FornecedorObj.Contato02" placeholder="Insira o nome do contato" />
                                    </div>
                                </div>
                                <div class="col-3">
                                    <div class="form-group">
                                        <label class="label font-weight-bold" asp-for="FornecedorObj.Telefone02"></label>
                                        <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.Telefone02"></span>
                                        <input class="form-control form-control-xs" asp-for="FornecedorObj.Telefone02" placeholder="Insira o telefone do contato" />
                                    </div>
                                </div>
                            </div>
                            <br/>
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label class="font-weight-bold" asp-for="FornecedorObj.Status">
                                            <span class="text-danger font-weight-light" asp-validation-for="FornecedorObj.Status"></span>
                                            <input type="checkbox" class="form-check-input" asp-for="FornecedorObj.Status" />
                                        Ativo/Inativo</label>
                                    </div>
                                    <br />
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-9">
                                    <div class="row">
                                        <div class="col-6">
                                            <button type="submit" value="Submit" asp-page-handler="Submit" class="btn btn-primary form-control">@(Model.FornecedorObj.FornecedorId != Guid.Empty ? "Atualizar" : "Criar")</button>

                                        </div>
                                        <div class="col-6">
                                            <a asp-page="./Index" class="btn btn-success form-control">Voltar à Lista</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section ScriptsBlock
{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<script>
    //Formata CNPJ
    //=============
    document.getElementById('cnpj').addEventListener('input', function (e) {
        var x = e.target.value.replace(/\D/g, '').match(/(\d{0,2})(\d{0,3})(\d{0,3})(\d{0,4})(\d{0,2})/);
        e.target.value = !x[2] ? x[1] : x[1] + '.' + x[2] + '.' + x[3] + '/' + x[4] + (x[5] ? '-' + x[5] : '');
    });
</script>

}